<img src= "https://i.pinimg.com/originals/3c/e9/c4/3ce9c4666219213f017a325c4acaa95f.png"
     align="left"
     width="250"/>
     
<h4 style='text-align:right;'> <span style="font-family:Times New Roman">Nom et Prénom:</span> </h4>     
<p style='text-align:right;'> <span style="font-family:Times New Roman">MAHAMAT Youssouf</span> </p>

# SUPPORT VECTOR MACHINES EN PYTHON

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import GridSearchCV

In [2]:
from sklearn import datasets

In [3]:
data_vin = datasets.load_wine()

In [4]:
print(data_vin)

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
 

In [5]:
data_vin.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names'])

In [6]:
print(data_vin['DESCR'])

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            1

In [7]:
print(data_vin['data'])

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]


In [8]:
print(data_vin['target_names'])

['class_0' 'class_1' 'class_2']


In [9]:
print(data_vin['target'])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [10]:
df_vin = pd.DataFrame(data_vin['data'], columns = data_vin['feature_names'])

In [11]:
df_vin

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  
0                            3.92   1065.0  
1                            3.40   1050.0  
2                            3.17   1185.0  
3                            3.45   1480.0  
4                            2.93    735.0  
..                            ...      ...  
173                          1.74    740.0  
174                          1.56    750.0  
175                          1.56    835.0  
176                          1.62    840.0  
177                          1.60    560.0  

[178 rows x 13 columns]

In [12]:
df_vin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
dtypes: fl

In [13]:
X = df_vin
y = data_vin['target']

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.25, 
                                                    random_state = 100)


In [15]:
X_train.shape

(133, 13)

In [16]:
X_test.shape

(45, 13)

In [17]:
model = SVC()

In [18]:
model.fit(X_train, y_train)

SVC()

In [19]:
predictions = model.predict(X_test)

In [20]:
model.score(X_train, y_train)

0.7293233082706767

In [21]:
model.score(X_test, y_test)

0.5333333333333333

In [22]:
print(confusion_matrix(y_test, predictions))

[[ 9  0  1]
 [ 2 14  1]
 [ 1 16  1]]


In [23]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.75      0.90      0.82        10
           1       0.47      0.82      0.60        17
           2       0.33      0.06      0.10        18

    accuracy                           0.53        45
   macro avg       0.52      0.59      0.50        45
weighted avg       0.48      0.53      0.44        45



In [24]:
grid_param = {'C': [0.1,1,5,10,15,20,30,40,50,100,1000,10000,100000],
             'gamma': [0.0000001, 0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1, 1]}

In [25]:
grid = GridSearchCV(SVC(), grid_param, verbose = 10)

In [26]:
grid.fit(X_train, y_train)

Fitting 5 folds for each of 104 candidates, totalling 520 fits
[CV 1/5; 1/104] START C=0.1, gamma=1e-07........................................
[CV 1/5; 1/104] END .........C=0.1, gamma=1e-07;, score=0.407 total time=   0.0s
[CV 2/5; 1/104] START C=0.1, gamma=1e-07........................................
[CV 2/5; 1/104] END .........C=0.1, gamma=1e-07;, score=0.407 total time=   0.0s
[CV 3/5; 1/104] START C=0.1, gamma=1e-07........................................
[CV 3/5; 1/104] END .........C=0.1, gamma=1e-07;, score=0.407 total time=   0.0s
[CV 4/5; 1/104] START C=0.1, gamma=1e-07........................................
[CV 4/5; 1/104] END .........C=0.1, gamma=1e-07;, score=0.385 total time=   0.0s
[CV 5/5; 1/104] START C=0.1, gamma=1e-07........................................
[CV 5/5; 1/104] END .........C=0.1, gamma=1e-07;, score=0.423 total time=   0.0s
[CV 1/5; 2/104] START C=0.1, gamma=1e-06........................................
[CV 1/5; 2/104] END .........C=0.1, gamma=1e-0

[CV 1/5; 18/104] END ..........C=5, gamma=1e-06;, score=0.667 total time=   0.0s
[CV 2/5; 18/104] START C=5, gamma=1e-06.........................................
[CV 2/5; 18/104] END ..........C=5, gamma=1e-06;, score=0.704 total time=   0.0s
[CV 3/5; 18/104] START C=5, gamma=1e-06.........................................
[CV 3/5; 18/104] END ..........C=5, gamma=1e-06;, score=0.778 total time=   0.0s
[CV 4/5; 18/104] START C=5, gamma=1e-06.........................................
[CV 4/5; 18/104] END ..........C=5, gamma=1e-06;, score=0.769 total time=   0.0s
[CV 5/5; 18/104] START C=5, gamma=1e-06.........................................
[CV 5/5; 18/104] END ..........C=5, gamma=1e-06;, score=0.654 total time=   0.0s
[CV 1/5; 19/104] START C=5, gamma=1e-05.........................................
[CV 1/5; 19/104] END ..........C=5, gamma=1e-05;, score=0.704 total time=   0.0s
[CV 2/5; 19/104] START C=5, gamma=1e-05.........................................
[CV 2/5; 19/104] END .......

[CV 3/5; 28/104] END ........C=10, gamma=0.0001;, score=0.815 total time=   0.0s
[CV 4/5; 28/104] START C=10, gamma=0.0001.......................................
[CV 4/5; 28/104] END ........C=10, gamma=0.0001;, score=0.923 total time=   0.0s
[CV 5/5; 28/104] START C=10, gamma=0.0001.......................................
[CV 5/5; 28/104] END ........C=10, gamma=0.0001;, score=0.731 total time=   0.0s
[CV 1/5; 29/104] START C=10, gamma=0.001........................................
[CV 1/5; 29/104] END .........C=10, gamma=0.001;, score=0.889 total time=   0.0s
[CV 2/5; 29/104] START C=10, gamma=0.001........................................
[CV 2/5; 29/104] END .........C=10, gamma=0.001;, score=0.593 total time=   0.0s
[CV 3/5; 29/104] START C=10, gamma=0.001........................................
[CV 3/5; 29/104] END .........C=10, gamma=0.001;, score=0.741 total time=   0.0s
[CV 4/5; 29/104] START C=10, gamma=0.001........................................
[CV 4/5; 29/104] END .......

[CV 3/5; 40/104] END .............C=15, gamma=1;, score=0.407 total time=   0.0s
[CV 4/5; 40/104] START C=15, gamma=1............................................
[CV 4/5; 40/104] END .............C=15, gamma=1;, score=0.385 total time=   0.0s
[CV 5/5; 40/104] START C=15, gamma=1............................................
[CV 5/5; 40/104] END .............C=15, gamma=1;, score=0.423 total time=   0.0s
[CV 1/5; 41/104] START C=20, gamma=1e-07........................................
[CV 1/5; 41/104] END .........C=20, gamma=1e-07;, score=0.667 total time=   0.0s
[CV 2/5; 41/104] START C=20, gamma=1e-07........................................
[CV 2/5; 41/104] END .........C=20, gamma=1e-07;, score=0.667 total time=   0.0s
[CV 3/5; 41/104] START C=20, gamma=1e-07........................................
[CV 3/5; 41/104] END .........C=20, gamma=1e-07;, score=0.741 total time=   0.0s
[CV 4/5; 41/104] START C=20, gamma=1e-07........................................
[CV 4/5; 41/104] END .......

[CV 2/5; 52/104] END ........C=30, gamma=0.0001;, score=0.630 total time=   0.0s
[CV 3/5; 52/104] START C=30, gamma=0.0001.......................................
[CV 3/5; 52/104] END ........C=30, gamma=0.0001;, score=0.889 total time=   0.0s
[CV 4/5; 52/104] START C=30, gamma=0.0001.......................................
[CV 4/5; 52/104] END ........C=30, gamma=0.0001;, score=0.885 total time=   0.0s
[CV 5/5; 52/104] START C=30, gamma=0.0001.......................................
[CV 5/5; 52/104] END ........C=30, gamma=0.0001;, score=0.769 total time=   0.0s
[CV 1/5; 53/104] START C=30, gamma=0.001........................................
[CV 1/5; 53/104] END .........C=30, gamma=0.001;, score=0.815 total time=   0.0s
[CV 2/5; 53/104] START C=30, gamma=0.001........................................
[CV 2/5; 53/104] END .........C=30, gamma=0.001;, score=0.593 total time=   0.0s
[CV 3/5; 53/104] START C=30, gamma=0.001........................................
[CV 3/5; 53/104] END .......

[CV 1/5; 63/104] END ...........C=40, gamma=0.1;, score=0.481 total time=   0.0s
[CV 2/5; 63/104] START C=40, gamma=0.1..........................................
[CV 2/5; 63/104] END ...........C=40, gamma=0.1;, score=0.444 total time=   0.0s
[CV 3/5; 63/104] START C=40, gamma=0.1..........................................
[CV 3/5; 63/104] END ...........C=40, gamma=0.1;, score=0.481 total time=   0.0s
[CV 4/5; 63/104] START C=40, gamma=0.1..........................................
[CV 4/5; 63/104] END ...........C=40, gamma=0.1;, score=0.385 total time=   0.0s
[CV 5/5; 63/104] START C=40, gamma=0.1..........................................
[CV 5/5; 63/104] END ...........C=40, gamma=0.1;, score=0.423 total time=   0.0s
[CV 1/5; 64/104] START C=40, gamma=1............................................
[CV 1/5; 64/104] END .............C=40, gamma=1;, score=0.407 total time=   0.0s
[CV 2/5; 64/104] START C=40, gamma=1............................................
[CV 2/5; 64/104] END .......

[CV 2/5; 75/104] END ........C=100, gamma=1e-05;, score=0.704 total time=   0.0s
[CV 3/5; 75/104] START C=100, gamma=1e-05.......................................
[CV 3/5; 75/104] END ........C=100, gamma=1e-05;, score=0.852 total time=   0.0s
[CV 4/5; 75/104] START C=100, gamma=1e-05.......................................
[CV 4/5; 75/104] END ........C=100, gamma=1e-05;, score=0.885 total time=   0.0s
[CV 5/5; 75/104] START C=100, gamma=1e-05.......................................
[CV 5/5; 75/104] END ........C=100, gamma=1e-05;, score=0.808 total time=   0.0s
[CV 1/5; 76/104] START C=100, gamma=0.0001......................................
[CV 1/5; 76/104] END .......C=100, gamma=0.0001;, score=0.889 total time=   0.0s
[CV 2/5; 76/104] START C=100, gamma=0.0001......................................
[CV 2/5; 76/104] END .......C=100, gamma=0.0001;, score=0.667 total time=   0.0s
[CV 3/5; 76/104] START C=100, gamma=0.0001......................................
[CV 3/5; 76/104] END .......

[CV 4/5; 85/104] START C=1000, gamma=0.001......................................
[CV 4/5; 85/104] END .......C=1000, gamma=0.001;, score=0.808 total time=   0.0s
[CV 5/5; 85/104] START C=1000, gamma=0.001......................................
[CV 5/5; 85/104] END .......C=1000, gamma=0.001;, score=0.731 total time=   0.0s
[CV 1/5; 86/104] START C=1000, gamma=0.01.......................................
[CV 1/5; 86/104] END ........C=1000, gamma=0.01;, score=0.741 total time=   0.0s
[CV 2/5; 86/104] START C=1000, gamma=0.01.......................................
[CV 2/5; 86/104] END ........C=1000, gamma=0.01;, score=0.556 total time=   0.0s
[CV 3/5; 86/104] START C=1000, gamma=0.01.......................................
[CV 3/5; 86/104] END ........C=1000, gamma=0.01;, score=0.704 total time=   0.0s
[CV 4/5; 86/104] START C=1000, gamma=0.01.......................................
[CV 4/5; 86/104] END ........C=1000, gamma=0.01;, score=0.692 total time=   0.0s
[CV 5/5; 86/104] START C=100

[CV 5/5; 96/104] END ..........C=10000, gamma=1;, score=0.423 total time=   0.0s
[CV 1/5; 97/104] START C=100000, gamma=1e-07....................................
[CV 1/5; 97/104] END .....C=100000, gamma=1e-07;, score=0.963 total time=   0.0s
[CV 2/5; 97/104] START C=100000, gamma=1e-07....................................
[CV 2/5; 97/104] END .....C=100000, gamma=1e-07;, score=0.963 total time=   0.0s
[CV 3/5; 97/104] START C=100000, gamma=1e-07....................................
[CV 3/5; 97/104] END .....C=100000, gamma=1e-07;, score=0.889 total time=   0.0s
[CV 4/5; 97/104] START C=100000, gamma=1e-07....................................
[CV 4/5; 97/104] END .....C=100000, gamma=1e-07;, score=0.962 total time=   0.0s
[CV 5/5; 97/104] START C=100000, gamma=1e-07....................................
[CV 5/5; 97/104] END .....C=100000, gamma=1e-07;, score=0.923 total time=   0.0s
[CV 1/5; 98/104] START C=100000, gamma=1e-06....................................
[CV 1/5; 98/104] END .....C=

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 5, 10, 15, 20, 30, 40, 50, 100, 1000,
                               10000, 100000],
                         'gamma': [1e-07, 1e-06, 1e-05, 0.0001, 0.001, 0.01,
                                   0.1, 1]},
             verbose=10)

In [27]:
grid.best_params_

{'C': 100000, 'gamma': 1e-06}

In [28]:
grid.best_score_

0.9552706552706554

In [29]:
grid_model = grid.best_estimator_

In [30]:
grid_predictions = grid_model.predict(X_test)

In [31]:
grid_model.score(X_test,y_test)

0.9111111111111111

In [32]:
print(confusion_matrix(y_test, grid_predictions))

[[10  0  0]
 [ 1 15  1]
 [ 0  2 16]]


In [33]:
print(classification_report(y_test, grid_predictions))

              precision    recall  f1-score   support

           0       0.91      1.00      0.95        10
           1       0.88      0.88      0.88        17
           2       0.94      0.89      0.91        18

    accuracy                           0.91        45
   macro avg       0.91      0.92      0.92        45
weighted avg       0.91      0.91      0.91        45

